# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1082, 622)
        self.loadButton = QtWidgets.QPushButton(Dialog)
        self.loadButton.setGeometry(QtCore.QRect(20, 20, 151, 23))
        self.loadButton.setObjectName("loadButton")
        self.img_before = QtWidgets.QLabel(Dialog)
        self.img_before.setGeometry(QtCore.QRect(130, 240, 401, 351))
        self.img_before.setFrameShape(QtWidgets.QFrame.Box)
        self.img_before.setText("")
        self.img_before.setObjectName("img_before")
        self.img_after = QtWidgets.QLabel(Dialog)
        self.img_after.setGeometry(QtCore.QRect(540, 240, 401, 351))
        self.img_after.setFrameShape(QtWidgets.QFrame.Box)
        self.img_after.setText("")
        self.img_after.setObjectName("img_after")
        self.text_img_before = QtWidgets.QLabel(Dialog)
        self.text_img_before.setGeometry(QtCore.QRect(230, 210, 191, 31))
        self.text_img_before.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_img_before.setAlignment(QtCore.Qt.AlignCenter)
        self.text_img_before.setObjectName("text_img_before")
        self.text_img_after = QtWidgets.QLabel(Dialog)
        self.text_img_after.setGeometry(QtCore.QRect(640, 210, 191, 31))
        self.text_img_after.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_img_after.setAlignment(QtCore.Qt.AlignCenter)
        self.text_img_after.setObjectName("text_img_after")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(360, 20, 151, 23))
        self.saveButton.setObjectName("saveButton")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 1061, 151))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.resizeImageButton = QtWidgets.QPushButton(self.tab_11)
        self.resizeImageButton.setGeometry(QtCore.QRect(170, 70, 151, 23))
        self.resizeImageButton.setObjectName("resizeImageButton")
        self.SaveSecondImageButton = QtWidgets.QPushButton(self.tab_11)
        self.SaveSecondImageButton.setGeometry(QtCore.QRect(330, 70, 151, 23))
        self.SaveSecondImageButton.setObjectName("SaveSecondImageButton")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_10)
        self.tabWidget_5.setGeometry(QtCore.QRect(80, 20, 901, 111))
        self.tabWidget_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_5.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.hSlider_addWeightedTwoImages = QtWidgets.QSlider(self.tab_20)
        self.hSlider_addWeightedTwoImages.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_addWeightedTwoImages.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_addWeightedTwoImages.setAccessibleDescription("")
        self.hSlider_addWeightedTwoImages.setMinimum(0)
        self.hSlider_addWeightedTwoImages.setMaximum(100)
        self.hSlider_addWeightedTwoImages.setPageStep(10)
        self.hSlider_addWeightedTwoImages.setProperty("value", 15)
        self.hSlider_addWeightedTwoImages.setSliderPosition(15)
        self.hSlider_addWeightedTwoImages.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_addWeightedTwoImages.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_addWeightedTwoImages.setTickInterval(10)
        self.hSlider_addWeightedTwoImages.setObjectName("hSlider_addWeightedTwoImages")
        self.AddWeightedTwoImagesButton = QtWidgets.QPushButton(self.tab_20)
        self.AddWeightedTwoImagesButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.AddWeightedTwoImagesButton.setObjectName("AddWeightedTwoImagesButton")
        self.AddWeightedTwoImagesBox = QtWidgets.QLineEdit(self.tab_20)
        self.AddWeightedTwoImagesBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.AddWeightedTwoImagesBox.setObjectName("AddWeightedTwoImagesBox")
        self.tabWidget_5.addTab(self.tab_20, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.AddWeightedConstButton = QtWidgets.QPushButton(self.tab_21)
        self.AddWeightedConstButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.AddWeightedConstButton.setObjectName("AddWeightedConstButton")
        self.AddWeightedConstBox = QtWidgets.QLineEdit(self.tab_21)
        self.AddWeightedConstBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.AddWeightedConstBox.setObjectName("AddWeightedConstBox")
        self.hSlider_addWeightedConst = QtWidgets.QSlider(self.tab_21)
        self.hSlider_addWeightedConst.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_addWeightedConst.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_addWeightedConst.setAccessibleDescription("")
        self.hSlider_addWeightedConst.setMinimum(1)
        self.hSlider_addWeightedConst.setMaximum(20)
        self.hSlider_addWeightedConst.setPageStep(10)
        self.hSlider_addWeightedConst.setProperty("value", 15)
        self.hSlider_addWeightedConst.setSliderPosition(15)
        self.hSlider_addWeightedConst.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_addWeightedConst.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_addWeightedConst.setTickInterval(10)
        self.hSlider_addWeightedConst.setObjectName("hSlider_addWeightedConst")
        self.tabWidget_5.addTab(self.tab_21, "")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.divideImagesButton = QtWidgets.QPushButton(self.tab_22)
        self.divideImagesButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.divideImagesButton.setObjectName("divideImagesButton")
        self.tabWidget_5.addTab(self.tab_22, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.hSlider_divideConst = QtWidgets.QSlider(self.tab_23)
        self.hSlider_divideConst.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_divideConst.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_divideConst.setAccessibleDescription("")
        self.hSlider_divideConst.setMinimum(1)
        self.hSlider_divideConst.setMaximum(100)
        self.hSlider_divideConst.setPageStep(10)
        self.hSlider_divideConst.setProperty("value", 15)
        self.hSlider_divideConst.setSliderPosition(15)
        self.hSlider_divideConst.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_divideConst.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_divideConst.setTickInterval(10)
        self.hSlider_divideConst.setObjectName("hSlider_divideConst")
        self.divideConstButton = QtWidgets.QPushButton(self.tab_23)
        self.divideConstButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.divideConstButton.setObjectName("divideConstButton")
        self.divideConstBox = QtWidgets.QLineEdit(self.tab_23)
        self.divideConstBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.divideConstBox.setObjectName("divideConstBox")
        self.tabWidget_5.addTab(self.tab_23, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.powImageButton = QtWidgets.QPushButton(self.tab_24)
        self.powImageButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.powImageButton.setObjectName("powImageButton")
        self.powImageBox = QtWidgets.QLineEdit(self.tab_24)
        self.powImageBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.powImageBox.setObjectName("powImageBox")
        self.tabWidget_5.addTab(self.tab_24, "")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_8)
        self.tabWidget_6.setGeometry(QtCore.QRect(80, 20, 901, 111))
        self.tabWidget_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_6.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.hSlider_uniform = QtWidgets.QSlider(self.tab_25)
        self.hSlider_uniform.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_uniform.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_uniform.setAccessibleDescription("")
        self.hSlider_uniform.setMinimum(1)
        self.hSlider_uniform.setMaximum(1000)
        self.hSlider_uniform.setPageStep(10)
        self.hSlider_uniform.setProperty("value", 100)
        self.hSlider_uniform.setSliderPosition(100)
        self.hSlider_uniform.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_uniform.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_uniform.setTickInterval(10)
        self.hSlider_uniform.setObjectName("hSlider_uniform")
        self.uniformButton = QtWidgets.QPushButton(self.tab_25)
        self.uniformButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.uniformButton.setObjectName("uniformButton")
        self.uniformBox = QtWidgets.QLineEdit(self.tab_25)
        self.uniformBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.uniformBox.setObjectName("uniformBox")
        self.tabWidget_6.addTab(self.tab_25, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.variousHeightButton = QtWidgets.QPushButton(self.tab_26)
        self.variousHeightButton.setGeometry(QtCore.QRect(90, 10, 151, 23))
        self.variousHeightButton.setObjectName("variousHeightButton")
        self.variousHeightBox = QtWidgets.QLineEdit(self.tab_26)
        self.variousHeightBox.setGeometry(QtCore.QRect(20, 10, 31, 21))
        self.variousHeightBox.setObjectName("variousHeightBox")
        self.hSlider_variousHeight = QtWidgets.QSlider(self.tab_26)
        self.hSlider_variousHeight.setGeometry(QtCore.QRect(290, 10, 581, 19))
        self.hSlider_variousHeight.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_variousHeight.setAccessibleDescription("")
        self.hSlider_variousHeight.setMinimum(1)
        self.hSlider_variousHeight.setMaximum(1000)
        self.hSlider_variousHeight.setPageStep(10)
        self.hSlider_variousHeight.setProperty("value", 100)
        self.hSlider_variousHeight.setSliderPosition(100)
        self.hSlider_variousHeight.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_variousHeight.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_variousHeight.setTickInterval(10)
        self.hSlider_variousHeight.setObjectName("hSlider_variousHeight")
        self.variousWidthBox = QtWidgets.QLineEdit(self.tab_26)
        self.variousWidthBox.setGeometry(QtCore.QRect(20, 50, 31, 21))
        self.variousWidthBox.setObjectName("variousWidthBox")
        self.variousWidthButton = QtWidgets.QPushButton(self.tab_26)
        self.variousWidthButton.setGeometry(QtCore.QRect(90, 50, 151, 23))
        self.variousWidthButton.setObjectName("variousWidthButton")
        self.hSlider_variousWidth = QtWidgets.QSlider(self.tab_26)
        self.hSlider_variousWidth.setGeometry(QtCore.QRect(290, 50, 581, 19))
        self.hSlider_variousWidth.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_variousWidth.setAccessibleDescription("")
        self.hSlider_variousWidth.setMinimum(1)
        self.hSlider_variousWidth.setMaximum(1000)
        self.hSlider_variousWidth.setPageStep(10)
        self.hSlider_variousWidth.setProperty("value", 100)
        self.hSlider_variousWidth.setSliderPosition(100)
        self.hSlider_variousWidth.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_variousWidth.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_variousWidth.setTickInterval(10)
        self.hSlider_variousWidth.setObjectName("hSlider_variousWidth")
        self.tabWidget_6.addTab(self.tab_26, "")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.rotateButton = QtWidgets.QPushButton(self.tab_27)
        self.rotateButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.rotateButton.setObjectName("rotateButton")
        self.hSlider_rotate = QtWidgets.QSlider(self.tab_27)
        self.hSlider_rotate.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_rotate.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_rotate.setAccessibleDescription("")
        self.hSlider_rotate.setMinimum(0)
        self.hSlider_rotate.setMaximum(360)
        self.hSlider_rotate.setPageStep(10)
        self.hSlider_rotate.setProperty("value", 100)
        self.hSlider_rotate.setSliderPosition(100)
        self.hSlider_rotate.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_rotate.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_rotate.setTickInterval(10)
        self.hSlider_rotate.setObjectName("hSlider_rotate")
        self.rotateBox = QtWidgets.QLineEdit(self.tab_27)
        self.rotateBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.rotateBox.setObjectName("rotateBox")
        self.tabWidget_6.addTab(self.tab_27, "")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.histogramButton = QtWidgets.QPushButton(self.tab_7)
        self.histogramButton.setGeometry(QtCore.QRect(30, 10, 151, 23))
        self.histogramButton.setObjectName("histogramButton")
        self.histogramLocalThresholdButton = QtWidgets.QPushButton(self.tab_7)
        self.histogramLocalThresholdButton.setGeometry(QtCore.QRect(30, 50, 151, 23))
        self.histogramLocalThresholdButton.setObjectName("histogramLocalThresholdButton")
        self.histogramGlobalThresholdButton = QtWidgets.QPushButton(self.tab_7)
        self.histogramGlobalThresholdButton.setGeometry(QtCore.QRect(30, 90, 151, 23))
        self.histogramGlobalThresholdButton.setObjectName("histogramGlobalThresholdButton")
        self.hSlider_histogramGlobalUpperThreshold = QtWidgets.QSlider(self.tab_7)
        self.hSlider_histogramGlobalUpperThreshold.setGeometry(QtCore.QRect(620, 90, 401, 19))
        self.hSlider_histogramGlobalUpperThreshold.setMaximum(255)
        self.hSlider_histogramGlobalUpperThreshold.setProperty("value", 120)
        self.hSlider_histogramGlobalUpperThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_histogramGlobalUpperThreshold.setObjectName("hSlider_histogramGlobalUpperThreshold")
        self.hSlider_histogramLocalUpperThreshold = QtWidgets.QSlider(self.tab_7)
        self.hSlider_histogramLocalUpperThreshold.setGeometry(QtCore.QRect(620, 50, 401, 19))
        self.hSlider_histogramLocalUpperThreshold.setMaximum(255)
        self.hSlider_histogramLocalUpperThreshold.setProperty("value", 120)
        self.hSlider_histogramLocalUpperThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_histogramLocalUpperThreshold.setObjectName("hSlider_histogramLocalUpperThreshold")
        self.hSlider_histogramLocalLowerThreshold = QtWidgets.QSlider(self.tab_7)
        self.hSlider_histogramLocalLowerThreshold.setGeometry(QtCore.QRect(190, 50, 401, 19))
        self.hSlider_histogramLocalLowerThreshold.setMaximum(255)
        self.hSlider_histogramLocalLowerThreshold.setProperty("value", 120)
        self.hSlider_histogramLocalLowerThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_histogramLocalLowerThreshold.setObjectName("hSlider_histogramLocalLowerThreshold")
        self.hSlider_histogramGlobalLowerThreshold = QtWidgets.QSlider(self.tab_7)
        self.hSlider_histogramGlobalLowerThreshold.setGeometry(QtCore.QRect(190, 90, 401, 19))
        self.hSlider_histogramGlobalLowerThreshold.setMaximum(255)
        self.hSlider_histogramGlobalLowerThreshold.setProperty("value", 120)
        self.hSlider_histogramGlobalLowerThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_histogramGlobalLowerThreshold.setObjectName("hSlider_histogramGlobalLowerThreshold")
        self.histogramGlobalUpperThresholdBox = QtWidgets.QLineEdit(self.tab_7)
        self.histogramGlobalUpperThresholdBox.setGeometry(QtCore.QRect(620, 70, 31, 21))
        self.histogramGlobalUpperThresholdBox.setObjectName("histogramGlobalUpperThresholdBox")
        self.histogramLocalUpperThresholdBox = QtWidgets.QLineEdit(self.tab_7)
        self.histogramLocalUpperThresholdBox.setGeometry(QtCore.QRect(620, 30, 31, 21))
        self.histogramLocalUpperThresholdBox.setObjectName("histogramLocalUpperThresholdBox")
        self.histogramGlobalLowerThresholdBox = QtWidgets.QLineEdit(self.tab_7)
        self.histogramGlobalLowerThresholdBox.setGeometry(QtCore.QRect(560, 70, 31, 21))
        self.histogramGlobalLowerThresholdBox.setObjectName("histogramGlobalLowerThresholdBox")
        self.histogramLocalLowerThresholdBox = QtWidgets.QLineEdit(self.tab_7)
        self.histogramLocalLowerThresholdBox.setGeometry(QtCore.QRect(560, 30, 31, 21))
        self.histogramLocalLowerThresholdBox.setObjectName("histogramLocalLowerThresholdBox")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_4.setGeometry(QtCore.QRect(80, 20, 901, 111))
        self.tabWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_4.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.hSlider_dilateBinary = QtWidgets.QSlider(self.tab_16)
        self.hSlider_dilateBinary.setGeometry(QtCore.QRect(290, 10, 581, 19))
        self.hSlider_dilateBinary.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_dilateBinary.setAccessibleDescription("")
        self.hSlider_dilateBinary.setMinimum(0)
        self.hSlider_dilateBinary.setMaximum(99)
        self.hSlider_dilateBinary.setPageStep(10)
        self.hSlider_dilateBinary.setProperty("value", 15)
        self.hSlider_dilateBinary.setSliderPosition(15)
        self.hSlider_dilateBinary.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_dilateBinary.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_dilateBinary.setTickInterval(10)
        self.hSlider_dilateBinary.setObjectName("hSlider_dilateBinary")
        self.dilateBinaryButton = QtWidgets.QPushButton(self.tab_16)
        self.dilateBinaryButton.setGeometry(QtCore.QRect(90, 10, 151, 23))
        self.dilateBinaryButton.setObjectName("dilateBinaryButton")
        self.dilateBinaryBox = QtWidgets.QLineEdit(self.tab_16)
        self.dilateBinaryBox.setGeometry(QtCore.QRect(20, 10, 31, 21))
        self.dilateBinaryBox.setObjectName("dilateBinaryBox")
        self.hSlider_dilateBinaryLowerThreshold = QtWidgets.QSlider(self.tab_16)
        self.hSlider_dilateBinaryLowerThreshold.setGeometry(QtCore.QRect(30, 60, 401, 19))
        self.hSlider_dilateBinaryLowerThreshold.setMaximum(255)
        self.hSlider_dilateBinaryLowerThreshold.setProperty("value", 120)
        self.hSlider_dilateBinaryLowerThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_dilateBinaryLowerThreshold.setObjectName("hSlider_dilateBinaryLowerThreshold")
        self.hSlider_dilateBinaryUpperThreshold = QtWidgets.QSlider(self.tab_16)
        self.hSlider_dilateBinaryUpperThreshold.setGeometry(QtCore.QRect(450, 60, 401, 19))
        self.hSlider_dilateBinaryUpperThreshold.setMaximum(255)
        self.hSlider_dilateBinaryUpperThreshold.setProperty("value", 255)
        self.hSlider_dilateBinaryUpperThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_dilateBinaryUpperThreshold.setObjectName("hSlider_dilateBinaryUpperThreshold")
        self.label = QtWidgets.QLabel(self.tab_16)
        self.label.setGeometry(QtCore.QRect(180, 40, 101, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_16)
        self.label_2.setGeometry(QtCore.QRect(610, 40, 91, 20))
        self.label_2.setObjectName("label_2")
        self.dilateBinaryLowerThresholdBox = QtWidgets.QLineEdit(self.tab_16)
        self.dilateBinaryLowerThresholdBox.setGeometry(QtCore.QRect(400, 40, 31, 21))
        self.dilateBinaryLowerThresholdBox.setObjectName("dilateBinaryLowerThresholdBox")
        self.dilateBinaryUpperThresholdBox = QtWidgets.QLineEdit(self.tab_16)
        self.dilateBinaryUpperThresholdBox.setGeometry(QtCore.QRect(450, 40, 31, 21))
        self.dilateBinaryUpperThresholdBox.setObjectName("dilateBinaryUpperThresholdBox")
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.erodeBinaryLowerThresholdBox = QtWidgets.QLineEdit(self.tab_17)
        self.erodeBinaryLowerThresholdBox.setGeometry(QtCore.QRect(400, 40, 31, 21))
        self.erodeBinaryLowerThresholdBox.setObjectName("erodeBinaryLowerThresholdBox")
        self.erodeBinaryUpperThresholdBox = QtWidgets.QLineEdit(self.tab_17)
        self.erodeBinaryUpperThresholdBox.setGeometry(QtCore.QRect(450, 40, 31, 21))
        self.erodeBinaryUpperThresholdBox.setObjectName("erodeBinaryUpperThresholdBox")
        self.hSlider_erodeBinaryUpperThreshold = QtWidgets.QSlider(self.tab_17)
        self.hSlider_erodeBinaryUpperThreshold.setGeometry(QtCore.QRect(450, 60, 401, 19))
        self.hSlider_erodeBinaryUpperThreshold.setMaximum(255)
        self.hSlider_erodeBinaryUpperThreshold.setProperty("value", 255)
        self.hSlider_erodeBinaryUpperThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_erodeBinaryUpperThreshold.setObjectName("hSlider_erodeBinaryUpperThreshold")
        self.hSlider_erodeBinaryLowerThreshold = QtWidgets.QSlider(self.tab_17)
        self.hSlider_erodeBinaryLowerThreshold.setGeometry(QtCore.QRect(30, 60, 401, 19))
        self.hSlider_erodeBinaryLowerThreshold.setMaximum(255)
        self.hSlider_erodeBinaryLowerThreshold.setProperty("value", 120)
        self.hSlider_erodeBinaryLowerThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_erodeBinaryLowerThreshold.setObjectName("hSlider_erodeBinaryLowerThreshold")
        self.erodeBinaryBox = QtWidgets.QLineEdit(self.tab_17)
        self.erodeBinaryBox.setGeometry(QtCore.QRect(20, 10, 31, 21))
        self.erodeBinaryBox.setObjectName("erodeBinaryBox")
        self.hSlider_erodeBinary = QtWidgets.QSlider(self.tab_17)
        self.hSlider_erodeBinary.setGeometry(QtCore.QRect(290, 10, 581, 19))
        self.hSlider_erodeBinary.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_erodeBinary.setAccessibleDescription("")
        self.hSlider_erodeBinary.setMinimum(0)
        self.hSlider_erodeBinary.setMaximum(99)
        self.hSlider_erodeBinary.setPageStep(10)
        self.hSlider_erodeBinary.setProperty("value", 15)
        self.hSlider_erodeBinary.setSliderPosition(15)
        self.hSlider_erodeBinary.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_erodeBinary.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_erodeBinary.setTickInterval(10)
        self.hSlider_erodeBinary.setObjectName("hSlider_erodeBinary")
        self.erodeBinaryButton = QtWidgets.QPushButton(self.tab_17)
        self.erodeBinaryButton.setGeometry(QtCore.QRect(90, 10, 151, 23))
        self.erodeBinaryButton.setObjectName("erodeBinaryButton")
        self.label_5 = QtWidgets.QLabel(self.tab_17)
        self.label_5.setGeometry(QtCore.QRect(610, 40, 91, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_17)
        self.label_6.setGeometry(QtCore.QRect(180, 40, 101, 20))
        self.label_6.setObjectName("label_6")
        self.tabWidget_4.addTab(self.tab_17, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(80, 20, 901, 111))
        self.tabWidget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_3.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.hSlider_dilateGrayscale = QtWidgets.QSlider(self.tab_14)
        self.hSlider_dilateGrayscale.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_dilateGrayscale.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_dilateGrayscale.setAccessibleDescription("")
        self.hSlider_dilateGrayscale.setMinimum(0)
        self.hSlider_dilateGrayscale.setMaximum(99)
        self.hSlider_dilateGrayscale.setPageStep(10)
        self.hSlider_dilateGrayscale.setProperty("value", 15)
        self.hSlider_dilateGrayscale.setSliderPosition(15)
        self.hSlider_dilateGrayscale.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_dilateGrayscale.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_dilateGrayscale.setTickInterval(10)
        self.hSlider_dilateGrayscale.setObjectName("hSlider_dilateGrayscale")
        self.dilateGrayscaleButton = QtWidgets.QPushButton(self.tab_14)
        self.dilateGrayscaleButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.dilateGrayscaleButton.setObjectName("dilateGrayscaleButton")
        self.dilateGrayscaleBox = QtWidgets.QLineEdit(self.tab_14)
        self.dilateGrayscaleBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.dilateGrayscaleBox.setObjectName("dilateGrayscaleBox")
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.erodeGrayscaleButton = QtWidgets.QPushButton(self.tab_15)
        self.erodeGrayscaleButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.erodeGrayscaleButton.setObjectName("erodeGrayscaleButton")
        self.erodeGrayscaleBox = QtWidgets.QLineEdit(self.tab_15)
        self.erodeGrayscaleBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.erodeGrayscaleBox.setObjectName("erodeGrayscaleBox")
        self.hSlider_erodeGrayscale = QtWidgets.QSlider(self.tab_15)
        self.hSlider_erodeGrayscale.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_erodeGrayscale.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_erodeGrayscale.setAccessibleDescription("")
        self.hSlider_erodeGrayscale.setMinimum(0)
        self.hSlider_erodeGrayscale.setMaximum(99)
        self.hSlider_erodeGrayscale.setPageStep(10)
        self.hSlider_erodeGrayscale.setProperty("value", 15)
        self.hSlider_erodeGrayscale.setSliderPosition(15)
        self.hSlider_erodeGrayscale.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_erodeGrayscale.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_erodeGrayscale.setTickInterval(10)
        self.hSlider_erodeGrayscale.setObjectName("hSlider_erodeGrayscale")
        self.tabWidget_3.addTab(self.tab_15, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(80, 20, 901, 111))
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.hSlider_median = QtWidgets.QSlider(self.tab_5)
        self.hSlider_median.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_median.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_median.setAccessibleDescription("")
        self.hSlider_median.setMinimum(0)
        self.hSlider_median.setMaximum(99)
        self.hSlider_median.setPageStep(10)
        self.hSlider_median.setProperty("value", 15)
        self.hSlider_median.setSliderPosition(15)
        self.hSlider_median.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_median.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_median.setTickInterval(10)
        self.hSlider_median.setObjectName("hSlider_median")
        self.medianButton = QtWidgets.QPushButton(self.tab_5)
        self.medianButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.medianButton.setObjectName("medianButton")
        self.medianBox = QtWidgets.QLineEdit(self.tab_5)
        self.medianBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.medianBox.setObjectName("medianBox")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gaussButton = QtWidgets.QPushButton(self.tab_4)
        self.gaussButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.gaussButton.setObjectName("gaussButton")
        self.gaussBox = QtWidgets.QLineEdit(self.tab_4)
        self.gaussBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.gaussBox.setObjectName("gaussBox")
        self.hSlider_gauss = QtWidgets.QSlider(self.tab_4)
        self.hSlider_gauss.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_gauss.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_gauss.setAccessibleDescription("")
        self.hSlider_gauss.setMinimum(0)
        self.hSlider_gauss.setMaximum(99)
        self.hSlider_gauss.setPageStep(10)
        self.hSlider_gauss.setProperty("value", 15)
        self.hSlider_gauss.setSliderPosition(15)
        self.hSlider_gauss.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_gauss.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_gauss.setTickInterval(10)
        self.hSlider_gauss.setObjectName("hSlider_gauss")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.hSlider_bilateral = QtWidgets.QSlider(self.tab_12)
        self.hSlider_bilateral.setGeometry(QtCore.QRect(290, 30, 581, 19))
        self.hSlider_bilateral.setFocusPolicy(QtCore.Qt.TabFocus)
        self.hSlider_bilateral.setAccessibleDescription("")
        self.hSlider_bilateral.setMinimum(0)
        self.hSlider_bilateral.setMaximum(99)
        self.hSlider_bilateral.setPageStep(10)
        self.hSlider_bilateral.setProperty("value", 15)
        self.hSlider_bilateral.setSliderPosition(15)
        self.hSlider_bilateral.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_bilateral.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider_bilateral.setTickInterval(10)
        self.hSlider_bilateral.setObjectName("hSlider_bilateral")
        self.bilateralButton = QtWidgets.QPushButton(self.tab_12)
        self.bilateralButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.bilateralButton.setObjectName("bilateralButton")
        self.bilateralBox = QtWidgets.QLineEdit(self.tab_12)
        self.bilateralBox.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.bilateralBox.setObjectName("bilateralBox")
        self.tabWidget_2.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.sobelButton = QtWidgets.QPushButton(self.tab_13)
        self.sobelButton.setGeometry(QtCore.QRect(90, 30, 151, 23))
        self.sobelButton.setObjectName("sobelButton")
        self.robertsButton = QtWidgets.QPushButton(self.tab_13)
        self.robertsButton.setGeometry(QtCore.QRect(430, 30, 151, 23))
        self.robertsButton.setObjectName("robertsButton")
        self.prewittButton = QtWidgets.QPushButton(self.tab_13)
        self.prewittButton.setGeometry(QtCore.QRect(260, 30, 151, 23))
        self.prewittButton.setObjectName("prewittButton")
        self.tabWidget_2.addTab(self.tab_13, "")
        self.tabWidget.addTab(self.tab, "")
        self.loadButton_2 = QtWidgets.QPushButton(Dialog)
        self.loadButton_2.setGeometry(QtCore.QRect(190, 20, 151, 23))
        self.loadButton_2.setObjectName("loadButton_2")
        self.equalizeHistButton = QtWidgets.QPushButton(Dialog)
        self.equalizeHistButton.setGeometry(QtCore.QRect(540, 20, 151, 23))
        self.equalizeHistButton.setObjectName("equalizeHistButton")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_5.setCurrentIndex(4)
        self.tabWidget_6.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loadButton.setText(_translate("Dialog", "Load image"))
        self.text_img_before.setText(_translate("Dialog", "loaded image"))
        self.text_img_after.setText(_translate("Dialog", "processed image"))
        self.saveButton.setText(_translate("Dialog", "Save image"))
        self.resizeImageButton.setText(_translate("Dialog", "unificate"))
        self.SaveSecondImageButton.setText(_translate("Dialog", "save second image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("Dialog", "unification"))
        self.AddWeightedTwoImagesButton.setText(_translate("Dialog", "add"))
        self.AddWeightedTwoImagesBox.setText(_translate("Dialog", "50"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_20), _translate("Dialog", "add two images"))
        self.AddWeightedConstButton.setText(_translate("Dialog", "add"))
        self.AddWeightedConstBox.setText(_translate("Dialog", "4"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_21), _translate("Dialog", "add image and value"))
        self.divideImagesButton.setText(_translate("Dialog", "dicide"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_22), _translate("Dialog", "divide images"))
        self.divideConstButton.setText(_translate("Dialog", "divide by value"))
        self.divideConstBox.setText(_translate("Dialog", "4"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_23), _translate("Dialog", "divide image by value"))
        self.powImageButton.setText(_translate("Dialog", "pow"))
        self.powImageBox.setText(_translate("Dialog", "4"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_24), _translate("Dialog", "power"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("Dialog", "sum"))
        self.uniformButton.setText(_translate("Dialog", "scale"))
        self.uniformBox.setText(_translate("Dialog", "50"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_25), _translate("Dialog", "1:1 scale"))
        self.variousHeightButton.setText(_translate("Dialog", "scale height"))
        self.variousHeightBox.setText(_translate("Dialog", "100"))
        self.variousWidthBox.setText(_translate("Dialog", "100"))
        self.variousWidthButton.setText(_translate("Dialog", "scale width"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_26), _translate("Dialog", "scale"))
        self.rotateButton.setText(_translate("Dialog", "rotate"))
        self.rotateBox.setText(_translate("Dialog", "90"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_27), _translate("Dialog", "rotate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "geometric operations"))
        self.histogramButton.setText(_translate("Dialog", "show hist"))
        self.histogramLocalThresholdButton.setText(_translate("Dialog", "local threshold"))
        self.histogramGlobalThresholdButton.setText(_translate("Dialog", "global threshold"))
        self.histogramGlobalUpperThresholdBox.setText(_translate("Dialog", "120"))
        self.histogramLocalUpperThresholdBox.setText(_translate("Dialog", "120"))
        self.histogramGlobalLowerThresholdBox.setText(_translate("Dialog", "120"))
        self.histogramLocalLowerThresholdBox.setText(_translate("Dialog", "120"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Histograms"))
        self.dilateBinaryButton.setText(_translate("Dialog", "Dilate"))
        self.dilateBinaryBox.setText(_translate("Dialog", "4"))
        self.label.setText(_translate("Dialog", "lower threshold"))
        self.label_2.setText(_translate("Dialog", "upper threshold"))
        self.dilateBinaryLowerThresholdBox.setText(_translate("Dialog", "120"))
        self.dilateBinaryUpperThresholdBox.setText(_translate("Dialog", "255"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("Dialog", "Dilate"))
        self.erodeBinaryLowerThresholdBox.setText(_translate("Dialog", "120"))
        self.erodeBinaryUpperThresholdBox.setText(_translate("Dialog", "255"))
        self.erodeBinaryBox.setText(_translate("Dialog", "4"))
        self.erodeBinaryButton.setText(_translate("Dialog", "Erode"))
        self.label_5.setText(_translate("Dialog", "upper threshold"))
        self.label_6.setText(_translate("Dialog", "lower threshold"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("Dialog", "Erosion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "binary morphology"))
        self.dilateGrayscaleButton.setText(_translate("Dialog", "Dilate"))
        self.dilateGrayscaleBox.setText(_translate("Dialog", "4"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), _translate("Dialog", "Dilate"))
        self.erodeGrayscaleButton.setText(_translate("Dialog", "Erosion"))
        self.erodeGrayscaleBox.setText(_translate("Dialog", "4"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_15), _translate("Dialog", "Erosion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "grayscale morphology"))
        self.medianButton.setText(_translate("Dialog", "median filter"))
        self.medianBox.setText(_translate("Dialog", "4"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "Median Blur"))
        self.gaussButton.setText(_translate("Dialog", "gaussian filter"))
        self.gaussBox.setText(_translate("Dialog", "4"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "Gaussian Blur"))
        self.bilateralButton.setText(_translate("Dialog", "bilateral filter"))
        self.bilateralBox.setText(_translate("Dialog", "4"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("Dialog", "Bilateral Filtering"))
        self.sobelButton.setText(_translate("Dialog", "Sobel"))
        self.robertsButton.setText(_translate("Dialog", "Roberts"))
        self.prewittButton.setText(_translate("Dialog", "Prewitt"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), _translate("Dialog", "highpass filters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "filters"))
        self.loadButton_2.setText(_translate("Dialog", "Load second image"))
        self.equalizeHistButton.setText(_translate("Dialog", "Normalize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

